using module ..\..\..\constants.ps1
using module ..\..\..\logic\arithmetic.ps1
using module ..\..\..\logic\block.ps1
using module ..\..\..\logic\call.ps1
using module ..\..\..\logic\comparison.ps1
using module ..\..\..\logic\context.ps1
using module ..\..\..\logic\duplication.ps1
using module ..\..\..\logic\flow.ps1
using module ..\..\..\logic\logging.ps1
using module ..\..\..\logic\memory.ps1
using module ..\..\..\logic\sha3.ps1
using module ..\..\..\logic\stack.ps1
using module ..\..\..\logic\storage.ps1
using module ..\..\..\logic\swap.ps1
using module ..\..\..\logic\system.ps1
using module ..\..\..\mnemonics.ps1
using module ..\..\..\opcode.ps1
using module ..\..\..\opcode_values.ps1

$FRONTIER_OPCODES = @{
    [opcode_values]::PUSH4 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push4($computation)
    }, [mnemonics]::PUSH4, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH5 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push5($computation)
    }, [mnemonics]::PUSH5, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH6 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push6($computation)
    }, [mnemonics]::PUSH6, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH7 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push7($computation)
    }, [mnemonics]::PUSH7, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH8 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push8($computation)
    }, [mnemonics]::PUSH8, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH9 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push9($computation)
    }, [mnemonics]::PUSH9, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH10 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push10($computation)
    }, [mnemonics]::PUSH10, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH11 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push11($computation)
    }, [mnemonics]::PUSH11, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH12 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push12($computation)
    }, [mnemonics]::PUSH12, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH13 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push13($computation)
    }, [mnemonics]::PUSH13, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH14 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push14($computation)
    }, [mnemonics]::PUSH14, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH15 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push15($computation)
    }, [mnemonics]::PUSH15, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH16 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push16($computation)
    }, [mnemonics]::PUSH16, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH17 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push17($computation)
    }, [mnemonics]::PUSH17, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH18 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push18($computation)
    }, [mnemonics]::PUSH18, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH19 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push19($computation)
    }, [mnemonics]::PUSH19, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH20 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push20($computation)
    }, [mnemonics]::PUSH20, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH21 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push21($computation)
    }, [mnemonics]::PUSH21, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH22 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push22($computation)
    }, [mnemonics]::PUSH22, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH23 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push23($computation)
    }, [mnemonics]::PUSH23, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH24 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push24($computation)
    }, [mnemonics]::PUSH24, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH25 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push25($computation)
    }, [mnemonics]::PUSH25, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH26 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push26($computation)
    }, [mnemonics]::PUSH26, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH27 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push27($computation)
    }, [mnemonics]::PUSH27, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH28 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push28($computation)
    }, [mnemonics]::PUSH28, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH29 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push29($computation)
    }, [mnemonics]::PUSH29, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH30 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push30($computation)
    }, [mnemonics]::PUSH30, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH31 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push31($computation)
    }, [mnemonics]::PUSH31, [constants]::GAS_VERYLOW)
    [opcode_values]::PUSH32 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [stack]::push32($computation)
    }, [mnemonics]::PUSH32, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP1 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup1($computation)
    }, [mnemonics]::DUP1, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP2 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup2($computation)
    }, [mnemonics]::DUP2, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP3 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup3($computation)
    }, [mnemonics]::DUP3, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP4 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup4($computation)
    }, [mnemonics]::DUP4, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP5 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup5($computation)
    }, [mnemonics]::DUP5, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP6 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup6($computation)
    }, [mnemonics]::DUP6, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP7 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup7($computation)
    }, [mnemonics]::DUP7, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP8 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup8($computation)
    }, [mnemonics]::DUP8, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP9 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup9($computation)
    }, [mnemonics]::DUP9, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP10 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup10($computation)
    }, [mnemonics]::DUP10, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP11 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup11($computation)
    }, [mnemonics]::DUP11, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP12 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup12($computation)
    }, [mnemonics]::DUP12, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP13 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup13($computation)
    }, [mnemonics]::DUP13, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP14 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup14($computation)
    }, [mnemonics]::DUP14, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP15 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup15($computation)
    }, [mnemonics]::DUP15, [constants]::GAS_VERYLOW)
    [opcode_values]::DUP16 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [duplication]::dup16($computation)
    }, [mnemonics]::DUP16, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP1 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap1($computation)
    }, [mnemonics]::SWAP1, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP2 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap2($computation)
    }, [mnemonics]::SWAP2, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP3 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap3($computation)
    }, [mnemonics]::SWAP3, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP4 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap4($computation)
    }, [mnemonics]::SWAP4, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP5 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap5($computation)
    }, [mnemonics]::SWAP5, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP6 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap6($computation)
    }, [mnemonics]::SWAP6, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP7 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap7($computation)
    }, [mnemonics]::SWAP7, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP8 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap8($computation)
    }, [mnemonics]::SWAP8, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP9 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap9($computation)
    }, [mnemonics]::SWAP9, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP10 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap10($computation)
    }, [mnemonics]::SWAP10, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP11 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap11($computation)
    }, [mnemonics]::SWAP11, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP12 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap12($computation)
    }, [mnemonics]::SWAP12, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP13 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap13($computation)
    }, [mnemonics]::SWAP13, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP14 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap14($computation)
    }, [mnemonics]::SWAP14, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP15 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap15($computation)
    }, [mnemonics]::SWAP15, [constants]::GAS_VERYLOW)
    [opcode_values]::SWAP16 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [swap]::swap16($computation)
    }, [mnemonics]::SWAP16, [constants]::GAS_VERYLOW)
    [opcode_values]::LOG0 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [logging]::log0($computation)
    }, [mnemonics]::LOG0, [constants]::GAS_LOG)
    [opcode_values]::LOG1 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [logging]::log1($computation)
    }, [mnemonics]::LOG1, [constants]::GAS_LOG)
    [opcode_values]::LOG2 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [logging]::log2($computation)
    }, [mnemonics]::LOG2, [constants]::GAS_LOG)
    [opcode_values]::LOG3 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [logging]::log3($computation)
    }, [mnemonics]::LOG3, [constants]::GAS_LOG)
    [opcode_values]::LOG4 = [Opcode]::AsOpcode({ param([Computation]$computation)
        [logging]::log4($computation)
    }, [mnemonics]::LOG4, [constants]::GAS_LOG)
    [opcode_values]::CREATE = [system.Create]::Configure("create", [mnemonics]::CREATE, [constants]::GAS_CREATE)
    [opcode_values]::CALL = [call.Call]::Configure("call", [mnemonics]::CALL, [constants]::GAS_CALL)
    [opcode_values]::CALLCODE = [call.CallCode]::Configure("callcode", [mnemonics]::CALLCODE, [constants]::GAS_CALL)
    [opcode_values]::RETURN = [Opcode]::AsOpcode({ param([Computation]$computation)
        [system]::return_op($computation)
    }, [mnemonics]::RETURN, [constants]::GAS_ZERO)
    [opcode_values]::SUICIDE = [Opcode]::AsOpcode({ param([Computation]$computation)
        [system]::suicide($computation)
    }, [mnemonics]::SUICIDE, [constants]::GAS_SUICIDE)
}
